# testing
TESTING_BORDER_SIZE = 0
TESTING_BORDER_TYPE = "solid"

# size, note: "iPhone size" according to google is 375x667... may have to adjust
MAIN_FRAME_ID = 1
WINDOW_WIDTH = 375
WINDOW_HEIGHT = 667

# footer styling
WINDOW_FOOTER_HEIGHT = 50 # -> the height of the "discover", "add", etc. buttons on the bottom
FOOTER_ICON_WIDTH = 25
FOOTER_ICON_HEIGHT = 25
FOOTER_BUTTON_PADDING = 10

FOOTER_HOME_BUTTON_SIZE = (25, 25)
FOOTER_RECIPES_BUTTON_SIZE = (25, 25)
FOOTER_ADD_BUTTON_SIZE = (40, 40)
FOOTER_DISCOVER_BUTTON_SIZE = (25, 25)
FOOTER_CATEGORY_BUTTON_SIZE = (20, 20)

FOOTER_BACKGROUND_COLOR = "#1D2B6A"

# header styling
HEADER_HEIGHT = 50
HEADER_ICON_WIDTH = 20
HEADER_ICON_HEIGHT = 20

HEADER_BUTTON_PADDING = 25

HEADER_BACKGROUND_COLOR = "#1D2B6A"

HEADER_MENU_BUTTON_SIZE = (20, 20)
HEADER_LOGO_BUTTON_SIZE = (150, 40)
HEADER_PROFILE_BUTTON_SIZE = (25, 25)


# MainFrame Styling
MAIN_RECIPE_BACKGROUND = "#01041A"

# color
RECIPE_CONTAINER_COLOR = "#01041A"
WINDOW_FOOTER_COLOR = "red"

# icon path
HOME_ICON_PATH = r"GUI\icons\home_icon.png"
RECIPES_ICON_PATH = r"GUI\icons\recipes_icon.png"
ADD_RECIPE_ICON_PATH = r"GUI\icons\add_recipe_icon.png"
DISCOVER_ICON_PATH = r"GUI\icons\discover_icon.png"
CATEGORY_ICON_PATH = r"GUI\icons\category_icon.png"
FOOTER_ICON_PATHS = [HOME_ICON_PATH, RECIPES_ICON_PATH, ADD_RECIPE_ICON_PATH, DISCOVER_ICON_PATH, CATEGORY_ICON_PATH]

HEADER_MENU_ICON_PATH = r"GUI\icons\header_menu_icon.png"
HEADER_LOGO_ICON_PATH = r"GUI\icons\header_logo.png"
HEADER_PROFILE_ICON_PATH = r"GUI\icons\header_profile_icon.png"
HEADER_ICON_PATHS = [HEADER_MENU_ICON_PATH, HEADER_LOGO_ICON_PATH, HEADER_PROFILE_ICON_PATH]